---
#################################################################################
# Test, build, and release/publish a Go app using the central PipelineTemplates #
# repository's go-build pipeline.                                               #
#################################################################################

resources:
  - name: pipelinetemplates
    type: git
    source:
      uri: ((templates_git_uri))
      branch: ((templates_git_branch))
      private_key: ((templates_git_private_key))

  - name: app
    type: git
    source:
      uri: ((git_uri))
      branch: ((git_branch))
      private_key: ((app_git_private_key))

  - name: go-image
    type: registry-image
    source:
      repository: golang
      tag: ((go_version))

jobs:
  - name: test-go-app
    public: true
    plan:
      - get: pipelinetemplates
        trigger: true
      - get: app
        trigger: true
      - get: go-image

      - task: test
        image: go-image
        file: pipelinetemplates/.concourse/go/go-build/tasks/test.yml
        params:
          MODULE_DIR: ((module_dir))
          TEST_PACKAGE: ((test_package))
          TEST_FLAGS: ((test_flags))
          CGO_ENABLED: ((cgo_enabled))

  - name: build-go-app
    public: true
    plan:
      - get: pipelinetemplates
        trigger: true
      - get: app
        passed: [test-go-app]
        trigger: true
      - get: go-image

      - task: build
        image: go-image
        file: pipelinetemplates/.concourse/go/go-build/tasks/build.yml
        params:
          MODULE_DIR: ((module_dir))
          BUILD_PACKAGE: ((build_package))
          BINARY_NAME: ((binary_name))
          PLATFORMS: ((platforms))
          BUILD_TAGS: ((build_tags))
          LDFLAGS: ((ldflags))
          OUTPUT_DIR: ((output_dir))
          CGO_ENABLED: ((cgo_enabled))

  - name: publish-go-app
    public: true
    plan:
      - get: pipelinetemplates
        trigger: true
      - get: app
        passed: [build-go-app]
        trigger: true
      - get: go-image

      - task: publish
        image: go-image
        file: pipelinetemplates/.concourse/go/go-build/tasks/publish.yml
        params:
          MODULE_DIR: ((module_dir))
          BINARY_NAME: ((binary_name))
          OUTPUT_DIR: ((output_dir))
