---
####################################
# Test building a Go app where the #
# app's entrypoint is in a subdir, #
# i.e. cmd/entrypoint/main.go.     #
####################################

name: Build example cmd/entrypoint app

on:
  workflow_dispatch:

jobs:
  build:
    uses: redjax/PipelineTemplates/.github/workflows/go-build.yml@fix/pipelinetemplates-checkout-ref
    with:
      module-dir: .
      build-package: ./cmd/example
      binary-name: ex
      platforms: linux/amd64,darwin/arm64
