---
name: Test Docker multi-arch build

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: redjax/pipelinetemplates-test-app2

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Build and publish app2 (multi-arch)
        uses: redjax/PipelineTemplates/.github/actions/docker-build-publish@feat/gh-docker-build-publish
        with:
          context: containers/app2
          dockerfile: containers/app2/Dockerfile
          image_name: redjax/pipelinetemplates-test-app2
          tags: |
            ghcr.io/redjax/pipelinetemplates-test-app2:${{ inputs.tag }}
            ghcr.io/redjax/pipelinetemplates-test-app2:sha-${{ github.sha }}
          push: ${{ inputs.push && 'true' || 'false' }}
          platforms: ${{ inputs.platforms }}
          build_args: |
            GIT_SHA=${{ github.sha }}
            BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          cache_from: ""
          cache_to: ""
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
