---
name: Test Hugo site release

on:
  workflow_run:
    workflows:
      - Test Hugo site build
    types:
      - completed

  workflow_dispatch:
    inputs:
      force-release:
        description: "Force the release job to run even without workflow_run."
        required: false
        type: boolean
        default: false

      build-run-id:
        description: "Optional build run id to release from."
        required: false
        type: string
        default: ""

permissions:
  actions: read
  contents: write

jobs:
  release:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' && inputs.force-release || github.event_name == 'push' }}
    uses: redjax/pipelinetemplates/.github/workflows/hugo-gh-release.yml@feat/release-publish-workflows
    with:
      versioned: false
      release-prefix: "site"
      artifact-name: "hugo-site"
      build-run-id: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.id || inputs.build-run-id }}
      build-repo: ${{ github.repository }}
    secrets:
      release-bot-pat: ${{ secrets.RELEASE_BOT_PAT }}
