---
#################################################
# Build a Go app that exists in a subdirectory, #
# i.e. apps/go-example/go.mod                   #
#################################################

name: Test build Go app (monorepo style)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build Go binaries
        uses: redjax/PipelineTemplates/.github/actions/go-build@gh/go-build/v0.0.1
        with:
          module-dir: apps/go-example # where go.mod lives
          build-package: ./cmd/example # package relative to module-dir
          go-version: "1.25.6"
          binary-name: ex
          platforms: linux/amd64,linux/arm64
          upload-artifacts: true
          artifact-name: example-dist
          ldflags: -X main.version=${{ github.sha }}
