---
name: Test Docker build & push to GHCR

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to use"
        required: false
        type: string
        default: "latest"
      push:
        description: "Push image to registry"
        required: false
        type: boolean
        default: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: redjax/pipelinetemplates-test-app1

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Build app1
        uses: redjax/PipelineTemplates/.github/actions/docker-build-publish@gh/docker-build-publish/v0.0.1
        with:
          context: containers/app1
          dockerfile: containers/app1/Dockerfile
          image_name: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ inputs.tag }}
          push: ${{ inputs.push && 'true' || 'false' }}
          platforms: linux/amd64
          build_args: |
            GIT_SHA=${{ github.sha }}
            BUILD_DATE=${{ github.run_id }}
          cache_from: ""
          cache_to: ""
          registry: ${{ env.REGISTRY }}
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
