---
name: Docker Build app2 (multi-arch)

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: redjax/pipelinetemplates-test-app2

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Build and publish app2 (multi-arch)
        uses: redjax/PipelineTemplates/.github/actions/docker-build-publish@feat/gh-docker-build-publish
        with:
          context: containers/app2
          dockerfile: containers/app2/Dockerfile
          image_name: ${{ env.IMAGE_NAME }}
          tags: |
            latest
            sha-${{ github.sha }}
          push: "true"
          platforms: linux/amd64,linux/arm64
          build_args: |
            GIT_SHA=${{ github.sha }}
            BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          cache_from: ""
          cache_to: ""
          registry: ${{ env.REGISTRY }}
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
