---
name: Test Hugo site build

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "apps/hugo-site/archetypes/**"
      - "apps/hugo-site/content/**"
      - "apps/hugo-site/data/**"
      - "apps/hugo-site/i18n/**"
      - "apps/hugo-site/static/**"
      - "apps/hugo-site/hugo.yml"
      - "apps/hugo-site/go.mod"
      - "apps/hugo-site/go.sum"

  workflow_dispatch:
    inputs:
      runner-img-or-label:
        description: "A runner image (i.e. ubuntu-latest) or self-hosted runner label (i.e. pipelinetemplates-test)"
        required: true
        type: string
        default: ubuntu-latest
      use-hugo-cache:
        type: boolean
        required: false
        default: true
      clean-hugo-cache:
        type: boolean
        required: false
        default: false

permissions:
  actions: write
  contents: write

jobs:
  build:
    uses: redjax/pipelinetemplates/.github/workflows/hugo-build.yml@main
    with:
      site-root: "apps/hugo-site"
      artifact-name: "hugo-site"
      public-dir: "apps/hugo-site/public"
      build-flags: "--gc --minify --enableGitInfo"
      checkout-ref: ""
      runner-image: ${{ inputs.runner-img-or-label || 'ubuntu-latest' }}
      use-cache: ${{ inputs.use-hugo-cache || true }}
      clean-cache: ${{ inputs.clean-hugo-cache || false }}
      debug-build-state: false
    secrets: inherit
