---
#################################################
# Test GoReleaser build in snapshot mode        #
# (builds all binaries without creating release)#
#################################################

name: Test GoReleaser (Snapshot)

on:
  workflow_dispatch:

jobs:
  goreleaser-snapshot:
    permissions:
      contents: write
      packages: write
      id-token: write
    uses: redjax/PipelineTemplates/.github/workflows/goreleaser-build.yml@github/goreleaser-build/v0.0.5
    with:
      goreleaser-config: .goreleaser.yml
      snapshot: true
      clean: true
      go-version: "1.25.6"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
