---
name: Test hello-world demo

on:
  workflow_dispatch:
    inputs:
      message:
        description: The message to print
        required: false
        type: string
        default: Hello from PipelineTemplates-test

jobs:
  call-template:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        uses: redjax/PipelineTemplates/.github/actions/hello@refactor/demo-hello-component
        with:
          message: ${{ inputs.message }}
