---
#################################################
# Test GoReleaser build in snapshot mode        #
# (builds all binaries without creating release)#
#################################################

name: Test GoReleaser (Snapshot)

on:
  workflow_dispatch:

jobs:
  goreleaser-snapshot:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Run GoReleaser snapshot build
        uses: redjax/PipelineTemplates/.github/actions/go-build@gh/goreleaser-build/v0.0.1
        with:
          goreleaser-config: .goreleaser.yml
          snapshot: "true"
          clean: "true"
          skip-validate: "false"
          skip-publish: "true" # snapshot build, no publish
          goreleaser-version: "latest"
          go-version: "1.25.6"
          working-directory: "."
          docker-build: "false"
          extra-args: ""
          dry-run: "false"
          release-notes: ""
          artifact-name: ""
          github-token: ${{ secrets.GITHUB_TOKEN }}
