---
name: Test Gotify Clickable Notification

on:
  workflow_dispatch:

jobs:
  notify:
    # uses: redjax/PipelineTemplates/.github/workflows/notify-gotify.yml@github/notify-gotify@v0.0.0
    uses: redjax/PipelineTemplates/.github/workflows/notify-gotify.yml@feat/gotify-notification

    with:
      title: Pipeline Test

      message: Click to open workflow run

      click-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      priority: 5

    secrets:
      gotify-url: ${{ secrets.GOTIFY_URL }}
      gotify-token: ${{ secrets.GOTIFY_TOKEN }}
