---
name: Test Docker build without push

on:
  workflow_dispatch:
    inputs:
      no_cache:
        description: Disable Docker build cache
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  packages: write

jobs:
  build-only:
    name: Build app1 without publishing

    permissions:
      contents: read
      packages: write

    uses: redjax/PipelineTemplates/.github/workflows/docker-build-publish.yml@main
    with:
      context: containers/app1
      dockerfile: containers/app1/Dockerfile
      image: ghcr.io/redjax/pipelinetemplates-test-app1
      tags: |
        ghcr.io/redjax/pipelinetemplates-test-app1:run-${{ github.run_id }}
      platforms: linux/amd64
      build_args: |
        GIT_SHA=${{ github.sha }}
        BUILD_DATE=${{ github.run_id }}
      labels: |
        org.opencontainers.image.source=https://github.com/${{ github.repository }}
        org.opencontainers.image.revision=${{ github.sha }}
      pull: true
      no_cache: ${{ inputs.no_cache }}
      cache_from: type=gha,scope=pipelinetemplates-test-app1
      cache_to: type=gha,mode=max,scope=pipelinetemplates-test-app1
      secrets: ""
      outputs: ""
      annotations: ""
      publish: false
    secrets:
      registry-token: ${{ secrets.GITHUB_TOKEN }}
