---
name: Test Docker build and push to GHCR

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Image tag to use
        required: false
        type: string
        default: latest

      push:
        description: Push image to registry
        required: false
        type: boolean
        default: true

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    name: Build app1

    permissions:
      contents: read
      packages: write

    uses: redjax/PipelineTemplates/.github/workflows/docker-build-publish.yml@feat/docker-gh-publish
    with:
      context: containers/app1
      dockerfile: containers/app1/Dockerfile
      image: ghcr.io/redjax/pipelinetemplates-test-app1
      tags: |
        ghcr.io/redjax/pipelinetemplates-test-app1:${{ inputs.tag }}
        ghcr.io/redjax/pipelinetemplates-test-app1:run-${{ github.run_id }}
      platforms: linux/amd64
      build_args: |
        GIT_SHA=${{ github.sha }}
        BUILD_DATE=${{ github.run_id }}
      labels: |
        org.opencontainers.image.source=https://github.com/${{ github.repository }}
        org.opencontainers.image.revision=${{ github.sha }}
      pull: true
      no_cache: false
      cache_from: type=gha,scope=pipelinetemplates-test-app1
      cache_to: type=gha,mode=max,scope=pipelinetemplates-test-app1
      secrets: ""
      outputs: ""
      annotations: ""
      publish: ${{ inputs.push }}
    secrets:
      registry-token: ${{ secrets.GITHUB_TOKEN }}
