---
####################################
# Test building a Go app where the #
# app's entrypoint is in a subdir, #
# i.e. cmd/entrypoint/main.go.     #
####################################

name: Test build example cmd/entrypoint app

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build Go binaries
        uses: redjax/PipelineTemplates/.github/actions/go-build@gh/go-build/v0.0.1
        with:
          module-dir: . # go.mod at repo root
          build-package: ./cmd/example # entrypoint package
          go-version: "1.25.6"
          binary-name: ex
          platforms: linux/amd64,darwin/arm64
          upload-artifacts: true
          artifact-name: example-dist
          ldflags: -X main.version=${{ github.sha }}
