---
name: Test Gotify Multipart Form Notification

on:
  workflow_dispatch:

jobs:
  notify:
    # uses: redjax/PipelineTemplates/.github/workflows/gotify-notification.yml@github/notify-gotify@v0.0.0
    uses: redjax/PipelineTemplates/.github/workflows/gotify-notification.yml@feat/gotify-notification

    with:
      gotify-url: ${{ secrets.GOTIFY_URL }}

      ## Forces multipart/form-data mode
      use-json: false

      title: Pipeline Test

      message: |
        This notification was sent using multipart/form-data mode.

        Only title, message, and priority are supported.

      priority: 2

    secrets:
      gotify-token: ${{ secrets.GOTIFY_TOKEN }}
