---
name: Test hello-world demo

on:
  workflow_dispatch:

jobs:
  call-template:
    uses: redjax/PipelineTemplates/.github/workflows/demo-hello.yml@refactor/demo-hello-component
    with:
      message: Hello from PipelineTemplates-Test
