---
name: Test Gotify Merged Extras Notification

on:
  workflow_dispatch:

jobs:
  notify:
    uses: redjax/PipelineTemplates/.github/workflows/notify-gotify.yml@github/notify-gotify/v0.0.1

    with:
      title: Pipeline Test
      gotify-url: ${{ vars.GOTIFY_URL }}
      message: Test notification with merged extras
      extras-json: |
        {
          "custom::ci": {
            "pipeline": "deploy",
            "environment": "production"
          }
        }

    secrets:
      gotify-token: ${{ secrets.GOTIFY_TOKEN }}
