---
#################################################
# Build a Go app that exists in a subdirectory, #
# i.e. apps/go-appname/go.mod                   #
#################################################

name: Build Go App (monorepo style)

on:
  workflow_dispatch:

jobs:
  build:
    uses: redjax/PipelineTemplates/.github/workflows/go-build.yml@github/go-build/v0.0.7
    with:
      module-dir: apps/go-example
      build-package: ./cmd/example
      binary-name: ex
      platforms: linux/amd64,linux/arm64
      upload-artifacts: true
      artifact-name: example-dist
      ldflags: -X main.version=${{ github.sha }}
