---
###################################################################
# Automatic & manual Hugo site pipeline.                          #
#                                                                 #
# Handles versioning, building, tagging/releasing, and publishing #
# the Hugo site in this repository.                               #
###################################################################

name: Hugo Site Main

on:
  push:
    branches:
      - main
    paths:
      - "apps/hugo-site/archetypes/**"
      - "apps/hugo-site/content/**"
      - "apps/hugo-site/data/**"
      - "apps/hugo-site/i18n/**"
      - "apps/hugo-site/static/**"
      - "apps/hugo-site/hugo.yml"
      - "apps/hugo-site/go.mod"
      - "apps/hugo-site/go.sum"

  workflow_dispatch:
    inputs:
      publish-gh-pages:
        type: boolean
        required: false
        default: false
      publish-to-branch:
        required: false
        default: false
        type: boolean
      branch-name:
        type: string
        required: false
        default: "gh-pages"
      publish-cf-pages:
        required: false
        default: false
        type: boolean
      runner-img-or-label:
        type: string
        default: ubuntu-latest

permissions:
  actions: write
  contents: write
  pages: write
  pull-requests: write
  id-token: write

jobs:
  ## Run on PR merge to main when Hugo files have changed
  auto:
    if: ${{ github.event_name == 'push' }}
    uses: redjax/pipelinetemplates/.github/workflows/hugo-site-auto-main.yml@feat/split-hugo-orchestrators
    with:
      site-root: "apps/hugo-site"
      versioned: true
      version-file: ".version"
      artifact-name: "hugo-site"
      release-prefix: "site"
      publish-gh-pages: true
      publish-to-branch: false
      publish-cf-pages: true
      branch-name: "gh-pages"
      cloudflare-pages-project: "pipelinetemplates-test"
      cloudflare-pages-branch: "feat/split-hugo-orchestrators"
      runner-image: "ubuntu-latest"
      templates-ref: "feat/split-hugo-orchestrators"
    secrets:
      release-bot-pat: ${{ secrets.RELEASE_BOT_PAT }}
      cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  ## Run on manual dispatch
  manual:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: redjax/pipelinetemplates/.github/workflows/hugo-site-manual-main.yml@feat/split-hugo-orchestrators
    with:
      site-root: "apps/hugo-site"
      versioned: true
      version-file: ".version"
      artifact-name: "hugo-site"
      release-prefix: "site"
      publish-gh-pages: ${{ inputs.publish-gh-pages }}
      publish-to-branch: ${{ inputs.publish-to-branch }}
      publish-cf-pages: ${{ inputs.publish-cf-pages }}
      branch-name: ${{ inputs.branch-name }}
      cloudflare-pages-project: "pipelinetemplates-test"
      cloudflare-pages-branch: "feat/split-hugo-orchestrators"
      runner-image: ${{ inputs.runner-img-or-label }}
      templates-ref: "feat/split-hugo-orchestrators"
    secrets:
      release-bot-pat: ${{ secrets.RELEASE_BOT_PAT }}
      cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
