---
##################################
# Test building a 'flat' Go app, #
# where the main.go is at the    #
# root of the repository.        #
##################################

name: Build Go App (flat)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build Go binaries
        uses: redjax/PipelineTemplates/.github/actions/go-build@feat/go-build-action
        with:
          module-dir: .
          build-package: .
          go-version: "1.25.6"
          binary-name: ex
          platforms: linux/amd64,linux/arm64
          upload-artifacts: true
          artifact-name: example-dist
          ldflags: -X main.version=${{ github.sha }}
