---
name: Test Gotify Image Notification

on:
  workflow_dispatch:

jobs:
  notify:
    # uses: redjax/PipelineTemplates/.github/workflows/notify-gotify.yml@github/notify-gotify@v0.0.0
    uses: redjax/PipelineTemplates/.github/workflows/notify-gotify.yml@feat/gotify-notification

    with:
      title: Pipeline Test
      gotify-url: ${{ vars.GOTIFY_URL }}
      message: Test notification with embedded image
      big-image-url: https://res.cloudinary.com/utiblog/image/upload/f_auto,q_auto/pipeline-welder_hero.webp
      priority: 5

    secrets:
      gotify-token: ${{ secrets.GOTIFY_TOKEN }}
